In [1]:
import numpy as np

In [2]:
def print_matrix():
    for i in a:
        print(i)
    print('\n')
    print(b)

# 1) Метод Гаусса

In [5]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

Прямой ход

In [ ]:
for k in range(n - 1):
    for i in range(k + 1, n):
        r = a[i][k] / a[k][k]
        for j in range(k, n):
            a[i][j] = a[i][j] - (r * a[k][j])
        b[i] = b[i] - (r * b[k])

In [ ]:
for i in range(n):
    for j in range(n):
        print(float('{:.2f}'.format(a[i][j])), end='    ')
    print('\n')
b

3.1    1.55    0.0    0.6    0.0    

0.0    2.33    0.93    -0.3    0.3    

0.0    -0.0    9.63    -0.81    1.38    

0.0    0.0    0.0    2.87    -0.15    

0.0    -0.0    0.0    0.0    2.85    



array([ -2.6195    ,  -0.39525   , -10.4836    ,   0.09577416,
        -1.76547452])

Обратный ход

In [299]:
array_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    array_1[k] = ((b[k] - sum([a[k][j] * array_1[j] for j in range(k + 1, n)])) / a[k][k])

In [300]:
for i in range(n):
    print(float('{:.10f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.10f}'.format(array_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  0.0  -0.62  

Определитель матрицы

In [301]:
det = 1
for i in range(n):
    for j in range(n):
        if i == j:
            det *= a[i][j]
print(det)

567.5496936075


# 2) Метод Жордана–Гаусса

In [181]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

In [182]:
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]


In [77]:
for k in range(n):
    for i in range(n):
        if i != k:
            r = a[i][k] / a[k][k]
            b[i] = b[i] - (r * b[k])
            for j in range(k, n):
                a[i][j] = a[i][j] - (r * a[k][j])

In [78]:
array_2 = [1] * 5 # x
for i in range(n):
    array_2[i] = (b[i]/a[i][i])

In [79]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(array_2[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  0.0  -0.62  

# 3) Метод LU–разложения

In [53]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

In [54]:
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]


In [55]:
L = np.eye(5)
U = np.zeros((5, 5))

In [56]:
for i in range(n):
    for j in range(n):
        tmp = 0.0
        # u
        if i <= j:
            U[i][j] = a[i][j] - sum([L[i][k]*U[k][j] for k in range(i)])
        # l
        else:
            L[i][j] = (a[i][j] - sum([L[i][k]*U[k][j] for k in range(j)]))/U[j][j]

In [57]:
array_3 = [1] * 5 # y
for k in range(n):
    array_3[k] = b[k] - sum([L[k][j] * array_3[j] for j in range(k)])

In [58]:
array_3_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    array_3_1[k] = (array_3[k] - sum([U[k][j] * array_3_1[j] for j in range(k + 1, n)]))/U[k][k]

In [59]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(array_3_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  -0.0  -0.62  

Определитель матрицы

In [60]:
det = 1
for i in range(n):
    for j in range(n):
        if i == j:
            det *= U[i][j]
print(det)

567.5496936075001


# 4) Метод квадратных корней (схема Холецкого)

In [269]:
NN = 16
j = 1.5 + 0.1 * NN
k = l = NN
m = 1
n = 5
    
a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
                  [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
                  [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
                  [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
                  [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
                  -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
                  -10 + 0.03 * j * j - 0.1 * l *j, 
                  -0.2 * k + 0.3 * j + 0.02 * j * j, 
                  0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

In [270]:
print_matrix()

[3.1  1.55 0.   3.2  0.  ]
[1.55 3.1  0.93 0.   1.6 ]
[ 0.    0.93 10.   -0.93  8.  ]
[ 3.2   0.   -0.93  3.1  -0.31]
[ 0.    1.6   8.   -0.31  3.1 ]


[ -2.6195  -2.511  -14.6717  -2.0778  -9.426 ]


In [271]:
import math

In [272]:
d = np.eye(5)
s = np.zeros((5, 5))

In [273]:
for i in range(n):
    d[i][i] = np.sign(a[i][i]-sum([s[p][i]*s[p][i]*d[p][p] for p in range(i)]))
    s[i][i] = np.sqrt(np.abs(a[i][i] - sum([s[p][i]*s[p][i]*d[p][p] for p in range(i)])))
    for j in range(i, n):
        s[i][j] = (a[i][j]-sum([s[p][i]*s[p][j]*d[p][p] for p in range(i)]))/(d[i][i]*s[i][i])

In [274]:
st = s.transpose().dot(d)

In [275]:
array_4 = [1] * 5 # y
for k in range(n):
    array_4[k] = (b[k] - sum([st[k][j] * array_4[j] for j in range(k)]))/st[k][k]

In [276]:
array_4_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    array_4_1[k] = (array_4[k] - sum([s[k][j] * array_4_1[j] for j in range(k + 1, n)]))/s[k][k]

In [277]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(array_4_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  0.0  -0.62  

# 5) Метод ортогонализации

In [289]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = [[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]]
b = [-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j]
linalg_solve = np.linalg.solve(a, b)

In [290]:
print_matrix()

[3.1, 1.55, 0, 0.6000000000000001, 0]
[1.55, 3.1, 0.9299999999999999, 0, 0.30000000000000004]
[0, 0.9299999999999999, 10, -0.9299999999999999, 1.5]
[0.6200000000000001, 0, -0.9299999999999999, 3.1, -0.31000000000000005]
[0, 0.31000000000000005, 1.55, -0.31000000000000005, 3.1]


[-2.6195, -1.705, -10.6417, 0.5021999999999999, -3.3759000000000006]


In [291]:
for i in range(n):
    a[i].append(-b[i])
a.append([float(i == n) for i in range(n + 1)])

In [292]:
a = np.array(a)

In [293]:
a

array([[ 3.1   ,  1.55  ,  0.    ,  0.6   ,  0.    ,  2.6195],
       [ 1.55  ,  3.1   ,  0.93  ,  0.    ,  0.3   ,  1.705 ],
       [ 0.    ,  0.93  , 10.    , -0.93  ,  1.5   , 10.6417],
       [ 0.62  ,  0.    , -0.93  ,  3.1   , -0.31  , -0.5022],
       [ 0.    ,  0.31  ,  1.55  , -0.31  ,  3.1   ,  3.3759],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  1.    ]])

In [294]:
u = np.array([[0.0 for _ in range(n + 1)] for _ in range(n + 1)])
v = np.array([[0.0 for _ in range(n + 1)] for _ in range(n + 1)])

In [295]:
u[0] = a[0]
v[0] = u[0]/np.sqrt(np.dot(u[0], u[0]))

In [296]:
for j in range(1, n + 1):
    u[j] = a[j] - sum([np.dot(a[j], v[i]) * v[i] for i in range(j)])
    v[j] = u[j] / np.sqrt(np.dot(u[j], u[j]))

In [297]:
y = np.array([0.0 for _ in range(n)])
for i in range(n):
    y[i] = u[n][i] / u[n][n] 
y

array([-1.00000000e+00,  3.10000000e-01, -1.00000000e+00, -7.84901658e-17,
       -6.20000000e-01])

In [298]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(y[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  -0.0  -0.62  

# 6) Метод прогонки

In [100]:
NN = 16
j = 1.5 + 0.1 * NN
k = l = 0
m = 1
n = 5
    
a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
                  [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
                  [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
                  [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
                  [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
r = np.array([-j + 0.05 * j * j, 
                  -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
                  -10 + 0.03 * j * j - 0.1 * l *j, 
                  -0.2 * k + 0.3 * j + 0.02 * j * j, 
                  0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, r)

In [101]:
print_matrix()

[3.1  1.55 0.   0.   0.  ]
[1.55 3.1  0.93 0.   0.  ]
[ 0.    0.93 10.   -0.93  0.  ]
[ 0.    0.   -0.93  3.1  -0.31]
[ 0.    0.    0.   -0.31  3.1 ]


[ 0.  -3.1  2.   0.   0. ]


In [102]:
c = np.array([0.0] * 5) 
d = np.array([0.0] * 5) 
b = np.array([0.0] * 5) 
for i in range(n):
    for j in range(n):
        if i == j:
            c[i] = a[i][j]
        elif i == j + 1:
            b[i] = a[i][j]
        elif i + 1 == j:
            d[i] = a[i][j]
c, d, b

(array([ 3.1,  3.1, 10. ,  3.1,  3.1]),
 array([ 1.55,  0.93, -0.93, -0.31,  0.  ]),
 array([ 0.  ,  1.55,  0.93, -0.93, -0.31]))

In [103]:
delta = np.array([0.0] * 5) 
_lambda = np.array([0.0] * 5) 

In [104]:
for i in range(n):
    delta[i] = -(d[i] / (c[i] + b[i] * delta[i-1]))
    _lambda[i] = ((r[i] - b[i] * _lambda[i-1]) / (c[i] + b[i] * delta[i-1]))
delta, _lambda

(array([-0.5       , -0.4       ,  0.09659327,  0.10298428, -0.        ]),
 array([-0.845     , -0.09      , -1.        ,  0.06385025, -0.62      ]))

In [105]:
x = np.array([0.0] * 5) 

In [106]:
x[n - 1] = ((r[n - 1] - b[n - 1] * _lambda[n - 2]) / (c[n - 1] + b[n - 1] * delta[n-2]))
for i in range(n - 2, -1, -1):
    x[i] = delta[i] * x[i + 1] + _lambda[i]

In [107]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(x[i])), end='  ')

-1.0  0.31  -1.0  -0.0  -0.62  

-1.0  0.31  -1.0  -0.0  -0.62  

# 7) Обратная матрица(методом Гаусса)

In [126]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5
a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])

linalg_solve = np.linalg.solve(a, b)

In [128]:
b = np.array([[float(i == j) for i in range(n)] for j in range(n)])
for k in range(n - 1):
        for i in range(k + 1, n):
            r = a[i][k] / a[k][k]
            for j in range(k, n):
                a[i][j] = a[i][j] - (r * a[k][j])
            b[i] = b[i] - (r * b[k])
            
x = np.array([[0.0 for _ in range(n)] for _ in range(n)])
for k in range(n - 1, -1, -1):
    for i in range(n):
        x[k][i] = ((b[k][i] - sum([a[k][j] * x[j][i] for j in range(k + 1, n)])) / a[k][k])
x

array([[ 0.45544618, -0.23230247,  0.01258681, -0.0835715 ,  0.00803334],
       [-0.23222322,  0.45165162, -0.03540522,  0.03198707, -0.02337796],
       [ 0.01228279, -0.0352635 ,  0.11332246,  0.02674479, -0.04874637],
       [-0.08656192,  0.03346273,  0.02643162,  0.3491528 ,  0.01888746],
       [ 0.00842473, -0.02418714, -0.05047754,  0.01834418,  0.35118037]])

In [127]:
print(np.linalg.inv(a))

[[ 0.45544618 -0.23230247  0.01258681 -0.0835715   0.00803334]
 [-0.23222322  0.45165162 -0.03540522  0.03198707 -0.02337796]
 [ 0.01228279 -0.0352635   0.11332246  0.02674479 -0.04874637]
 [-0.08656192  0.03346273  0.02643162  0.3491528   0.01888746]
 [ 0.00842473 -0.02418714 -0.05047754  0.01834418  0.35118037]]


# 8) Решение СЛАУ в комплексном пространстве

In [370]:
NN = 16
i = 1.5 + 0.1 * NN

a = np.array([[1 - i * 1j, 0, -i * 1j], 
              [-i - 2j, -i * 1j, 2 + i * 1j], 
              [1j, 2, i]])
b =  np.array([1 + i - 3 * i * 1j, 
              -3 * i + 4 + 2 * i * 1j, 
              2 * i + (i - 1) * 1j])

n = len(a)
linalg_solve = np.linalg.solve(a, b)

In [371]:
print_matrix()

[ 1.-3.1j  0.+0.j  -0.-3.1j]
[-3.1-2.j  -0. -3.1j  2. +3.1j]
[0. +1.j 2. +0.j 3.1+0.j]


[ 4.1-9.3j -5.3+6.2j  6.2+2.1j]


In [372]:
A_real = np.array([[0.0 for _ in range(n)] for _ in range(n)])
A_imag = np.array([[0.0 for _ in range(n)] for _ in range(n)])
b_real = np.array([0.0 for _ in range(n)])
b_imag = np.array([0.0 for _ in range(n)])

In [373]:
for i in range(n):
    b_real[i] = b[i].real
    b_imag[i] = b[i].imag
    for j in range(n):
        A_real[i][j] = a[i][j].real
        A_imag[i][j] = a[i][j].imag

In [374]:
A_real, A_imag, b_real, b_imag

(array([[ 1. ,  0. , -0. ],
        [-3.1, -0. ,  2. ],
        [ 0. ,  2. ,  3.1]]),
 array([[-3.1,  0. , -3.1],
        [-2. , -3.1,  3.1],
        [ 1. ,  0. ,  0. ]]),
 array([ 4.1, -5.3,  6.2]),
 array([-9.3,  6.2,  2.1]))

In [375]:
C1 = np.concatenate((A_real, A_imag))
C2 = np.concatenate((-A_imag, A_real))
C = np.concatenate((C1, C2), axis = 1)
d = np.concatenate((b_real, b_imag))
C, d

(array([[ 1. ,  0. , -0. ,  3.1, -0. ,  3.1],
        [-3.1, -0. ,  2. ,  2. ,  3.1, -3.1],
        [ 0. ,  2. ,  3.1, -1. , -0. , -0. ],
        [-3.1,  0. , -3.1,  1. ,  0. , -0. ],
        [-2. , -3.1,  3.1, -3.1, -0. ,  2. ],
        [ 1. ,  0. ,  0. ,  0. ,  2. ,  3.1]]),
 array([ 4.1, -5.3,  6.2, -9.3,  6.2,  2.1]))

### Воспользуемся методом ортогонализации (5)

In [376]:
tmp = [[C[i][j] for j in range(2 * n)] for i in range(2 * n)]
for i in range(2 * n):
    tmp[i].append(-d[i])
tmp.append([float(i == (2 * n)) for i in range(2 * n + 1)])
C = np.array([[tmp[i][j] for j in range(2 * n + 1)] for i in range(2 * n + 1)])
C

array([[ 1. ,  0. , -0. ,  3.1, -0. ,  3.1, -4.1],
       [-3.1, -0. ,  2. ,  2. ,  3.1, -3.1,  5.3],
       [ 0. ,  2. ,  3.1, -1. , -0. , -0. , -6.2],
       [-3.1,  0. , -3.1,  1. ,  0. , -0. ,  9.3],
       [-2. , -3.1,  3.1, -3.1, -0. ,  2. , -6.2],
       [ 1. ,  0. ,  0. ,  0. ,  2. ,  3.1, -2.1],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ]])

In [377]:
u = np.array([[0.0 for _ in range(2 * n + 1)] for _ in range(2 * n + 1)])
v = np.array([[0.0 for _ in range(2 * n + 1)] for _ in range(2 * n + 1)])

In [378]:
u[0] = C[0]
v[0] = u[0]/np.sqrt(np.dot(u[0], u[0]))

In [379]:
for j in range(1, 2 * n + 1):
    u[j] = C[j] - sum([np.dot(C[j], v[i]) * v[i] for i in range(j)])
    v[j] = u[j] / np.sqrt(np.dot(u[j], u[j]))

In [380]:
y = np.array([0.0 for _ in range(2 * n)])
for i in range(2 * n):
    y[i] = u[2 * n][i] / u[2 * n][2 * n] 

In [381]:
for i in linalg_solve:
    print('{:.5f}'.format(i.real) + ' ' + '{:.5f}'.format(i.imag) + 'i')
print('\n')
for i in range(3):
    print('{:.5f}'.format(y[i]) + ' ' + '{:.5f}'.format(y[i+3]) + 'i') 

1.00000 -0.00000i
-0.00000 -1.00000i
2.00000 1.00000i


1.00000 -0.00000i
-0.00000 -1.00000i
2.00000 1.00000i
