In [3]:
import numpy as np

In [4]:
def print_matrix():
    for i in a:
        print(i)
    print('\n')
    print(b)

# 1) Метод Гаусса

In [325]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

Прямой ход

In [297]:
for k in range(n - 1):
    for i in range(k + 1, n):
        r = a[i][k] / a[k][k]
        for j in range(k, n):
            a[i][j] = a[i][j] - (r * a[k][j])
        b[i] = b[i] - (r * b[k])

In [298]:
for i in range(n):
    for j in range(n):
        print(float('{:.2f}'.format(a[i][j])), end='    ')
    print('\n')
b

3.1    1.55    0.0    0.6    0.0    

0.0    2.33    0.93    -0.3    0.3    

0.0    -0.0    9.63    -0.81    1.38    

0.0    0.0    0.0    2.87    -0.15    

0.0    -0.0    0.0    0.0    2.85    



array([ -2.6195    ,  -0.39525   , -10.4836    ,   0.09577416,
        -1.76547452])

Обратный ход

In [299]:
array_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    array_1[k] = ((b[k] - sum([a[k][j] * array_1[j] for j in range(k + 1, n)])) / a[k][k])

In [300]:
for i in range(n):
    print(float('{:.10f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.10f}'.format(array_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  0.0  -0.62  

Определитель матрицы

In [301]:
det = 1
for i in range(n):
    for j in range(n):
        if i == j:
            det *= a[i][j]
print(det)

567.5496936075


# 2) Метод Жордана–Гаусса

In [75]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

In [76]:
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]


In [77]:
for k in range(n):
    for i in range(n):
        if i != k:
            r = a[i][k] / a[k][k]
            b[i] = b[i] - (r * b[k])
            for j in range(k, n):
                a[i][j] = a[i][j] - (r * a[k][j])

In [78]:
array_2 = [1] * 5 # x
for i in range(n):
    array_2[i] = (b[i]/a[i][i])

In [79]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(array_2[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  0.0  -0.62  

# 3) Метод LU–разложения

In [53]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

In [54]:
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]


In [55]:
L = np.eye(5)
U = np.zeros((5, 5))

In [56]:
for i in range(n):
    for j in range(n):
        tmp = 0.0
        # u
        if i <= j:
            U[i][j] = a[i][j] - sum([L[i][k]*U[k][j] for k in range(i)])
        # l
        else:
            L[i][j] = (a[i][j] - sum([L[i][k]*U[k][j] for k in range(j)]))/U[j][j]

In [57]:
array_3 = [1] * 5 # y
for k in range(n):
    array_3[k] = b[k] - sum([L[k][j] * array_3[j] for j in range(k)])

In [58]:
array_3_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    array_3_1[k] = (array_3[k] - sum([U[k][j] * array_3_1[j] for j in range(k + 1, n)]))/U[k][k]

In [59]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(array_3_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  -0.0  -0.62  

Определитель матрицы

In [60]:
det = 1
for i in range(n):
    for j in range(n):
        if i == j:
            det *= U[i][j]
print(det)

567.5496936075001


# 4) Метод квадратных корней (схема Холецкого)

In [234]:
NN = 16
j = 1.5 + 0.1 * NN
k = l = NN
m = 1
n = 5
    
a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
                  [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
                  [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
                  [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
                  [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
                  -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
                  -10 + 0.03 * j * j - 0.1 * l *j, 
                  -0.2 * k + 0.3 * j + 0.02 * j * j, 
                  0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

In [235]:
print_matrix()

[3.1  1.55 0.   3.2  0.  ]
[1.55 3.1  0.93 0.   1.6 ]
[ 0.    0.93 10.   -0.93  8.  ]
[ 3.2   0.   -0.93  3.1  -0.31]
[ 0.    1.6   8.   -0.31  3.1 ]


[ -2.6195  -2.511  -14.6717  -2.0778  -9.426 ]


In [236]:
import math

In [237]:
d = np.eye(5)
s = np.zeros((5, 5))

In [238]:
for i in range(n):
    d[i][i] = np.sign(a[i][i]-sum([s[p][i]*s[p][i]*d[p][p] for p in range(i)]))
    s[i][i] = np.sqrt(np.abs(a[i][i] - sum([s[p][i]*s[p][i]*d[p][p] for p in range(i)])))
    for j in range(i, n):
        s[i][j] = (a[i][j]-sum([s[p][i]*s[p][j]*d[p][p] for p in range(i)]))/(d[i][i]*s[i][i])

In [239]:
st = s.transpose().dot(d)

In [240]:
array_4 = [1] * 5 # y
for k in range(n):
    array_4[k] = (b[k] - sum([st[k][j] * array_4[j] for j in range(k)]))/st[k][k]

In [241]:
array_4_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    array_4_1[k] = (array_4[k] - sum([s[k][j] * array_4_1[j] for j in range(k + 1, n)]))/s[k][k]

In [242]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(array_4_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  0.0  -0.62  

# 5) Метод ортогонализации

In [131]:
pass

# 6) Метод прогонки

In [5]:
NN = 16
j = 1.5 + 0.1 * NN
k = l = 0
m = 1
n = 5
    
a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
                  [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
                  [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
                  [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
                  [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
r = np.array([-j + 0.05 * j * j, 
                  -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
                  -10 + 0.03 * j * j - 0.1 * l *j, 
                  -0.2 * k + 0.3 * j + 0.02 * j * j, 
                  0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, r)

In [6]:
print_matrix()

[3.1  1.55 0.   0.   0.  ]
[1.55 3.1  0.93 0.   0.  ]
[ 0.    0.93 10.   -0.93  0.  ]
[ 0.    0.   -0.93  3.1  -0.31]
[ 0.    0.    0.   -0.31  3.1 ]




NameError: name 'b' is not defined

In [7]:
c = np.array([0.0] * 5) 
d = np.array([0.0] * 5) 
b = np.array([0.0] * 5) 
for i in range(n):
    for j in range(n):
        if i == j:
            c[i] = a[i][j]
        elif i == j + 1:
            b[i] = a[i][j]
        elif i + 1 == j:
            d[i] = a[i][j]
c, d, b

(array([ 3.1,  3.1, 10. ,  3.1,  3.1]),
 array([ 1.55,  0.93, -0.93, -0.31,  0.  ]),
 array([ 0.  ,  1.55,  0.93, -0.93, -0.31]))

In [8]:
delta = np.array([0.0] * 5) 
_lambda = np.array([0.0] * 5) 

In [9]:
for i in range(n):
    delta[i] = -(d[i] / (c[i] + b[i] * delta[i-1]))
    _lambda[i] = ((r[i] - b[i] * _lambda[i-1]) / (c[i] + b[i] * delta[i-1]))
delta, _lambda

(array([-0.5       , -0.4       ,  0.09659327,  0.10298428, -0.        ]),
 array([-0.845     , -0.09      , -1.        ,  0.06385025, -0.62      ]))

In [10]:
x = np.array([0.0] * 5) 

In [11]:
x[n - 1] = ((r[n - 1] - b[n - 1] * _lambda[n - 2]) / (c[n - 1] + b[n - 1] * delta[n-2]))
for i in range(n - 2, -1, -1):
    x[i] = delta[i] * x[i + 1] + _lambda[i]

In [12]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(x[i])), end='  ')

-1.0  0.31  -1.0  -0.0  -0.62  

-1.0  0.31  -1.0  -0.0  -0.62  