In [246]:
import numpy as np

In [247]:
def create_matrix():
    NN = 16
    j = 1.5 + 0.1 * NN
    k = j
    l = k - 0.1
    m = 1
    n = 5
    global a, b
    
    a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
                  [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
                  [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
                  [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
                  [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
    b = np.array([-j + 0.05 * j * j, 
                  -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
                  -10 + 0.03 * j * j - 0.1 * l *j, 
                  -0.2 * k + 0.3 * j + 0.02 * j * j, 
                  0.01 * k * j - 0.5 * k - 0.2 * j * j])
    

In [248]:
def print_matrix():
    for i in a:
        print(i)
    print('\n')
    print(b)

In [249]:
create_matrix()
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]


In [250]:
linalg_solve = np.linalg.solve(a, b)

# 1) Метод Гаусса

Прямой ход

In [251]:
for k in range(n - 1):
    for i in range(k + 1, n):
        r = a[i][k] / a[k][k]
        for j in range(k, n):
            a[i][j] = a[i][j] - (r * a[k][j])
        b[i] = b[i] - (r * b[k])

In [252]:
for i in range(n):
    for j in range(n):
        print(float('{:.2f}'.format(a[i][j])), end='  ')
    print('\n')
b

3.1  1.55  0.0  0.6  0.0  

0.0  2.33  0.93  -0.3  0.3  

0.0  -0.0  9.63  -0.81  1.38  

0.0  0.0  0.0  2.87  -0.15  

0.0  -0.0  0.0  0.0  2.85  



array([ -2.6195    ,  -0.39525   , -10.4836    ,   0.09577416,
        -1.76547452])

Обратный ход

In [253]:
array_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    tmp = 0
    for j in range(k + 1, n):
        tmp += a[k][j] * array_1[j]
    array_1[k] = ((b[k] - tmp) / a[k][k])

In [254]:
for i in range(n):
    print(float('{:.10f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.10f}'.format(array_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  0.0  -0.62  

# 2) Метод Жордана–Гаусса

In [255]:
create_matrix()
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]


In [256]:
for k in range(n - 1):
    for i in range(k + 1, n):
        r = a[i][k] / a[k][k]
        for j in range(k, n):
            a[i][j] = a[i][j] - (r * a[k][j])
            a[j][i] = a[j][i] - (r * a[j][k])
        b[i] = b[i] - (r * b[k])

In [257]:
for i in range(n):
    for j in range(n):
        print(float('{:.2f}'.format(a[i][j])), end='  ')
    print('\n')
b

3.1  0.0  0.0  -0.02  0.0  

0.0  3.1  0.0  0.01  -0.01  

0.0  0.0  10.0  -0.0  -0.05  

0.0  0.0  0.0  3.1  -0.0  

0.0  0.0  0.0  0.0  3.11  



array([ -2.6195    ,  -0.39525   , -10.523125  ,   0.10578944,
        -1.79778531])

In [258]:
array_2 = [1] * 5 # x
for i in range(n):
    array_2[i] = (b[i]/a[i][i])

In [259]:
for i in range(n):
    print(float('{:.2f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.2f}'.format(array_2[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-0.84  -0.13  -1.05  0.03  -0.58  

# 3) Метод LU–разложения

In [260]:
from scipy.linalg import lu

In [261]:
create_matrix()
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]


In [262]:
P,L,U = lu(a)

In [263]:
P, L, U

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.5       ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.4       ,  1.        ,  0.        ,  0.        ],
        [ 0.2       , -0.13333333, -0.08371417,  1.        ,  0.        ],
        [ 0.        ,  0.13333333,  0.14810968, -0.05223578,  1.        ]]),
 array([[ 3.1       ,  1.55      ,  0.        ,  0.6       ,  0.        ],
        [ 0.        ,  2.325     ,  0.93      , -0.3       ,  0.3       ],
        [ 0.        ,  0.        ,  9.628     , -0.81      ,  1.38      ],
        [ 0.        ,  0.        ,  0.        ,  2.87219152, -0.15447445],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  2.84753955]]))

In [264]:
# u
for i in range(n):
    for j in range(n):
        tmp = 0
        for k in range(i-1):
            tmp += L[i][k]*U[k][j]
        U[i][j] = a[i][j] - tmp

In [265]:
# l
for i in range(n):
    for j in range(n):
        tmp = 0
        for k in range(j-1):
            tmp += L[i][k]*U[k][j]
        L[i][j] = (a[i][j] - tmp)/U[j][j]

In [266]:
array_3 = [1] * 5 # y
for k in range(n):
    tmp = 0
    for j in range(k - 1):
        tmp += L[k][j] * array_3[j]
    array_3[k] = b[k] - tmp

In [267]:
array_3_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    tmp = 0
    for j in range(k + 1, n):
        tmp += U[k][j] * array_3_1[j]
    array_3_1[k] = (array_3[k] - tmp)/U[k][k]

In [268]:
for i in range(n):
    print(float('{:.2f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.2f}'.format(array_3_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-0.8  -0.21  -0.95  0.29  -0.55  

# 4) Метод квадратных корней

In [269]:
create_matrix()
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]
