In [5]:
import numpy as np

In [6]:
def print_matrix():
    for i in a:
        print(i)
    print('\n')
    print(b)

# 1) Метод Гаусса

In [159]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

Прямой ход

In [161]:
for k in range(n - 1):
    for i in range(k + 1, n):
        r = a[i][k] / a[k][k]
        for j in range(k, n):
            a[i][j] = a[i][j] - (r * a[k][j])
        b[i] = b[i] - (r * b[k])

In [691]:
for i in range(n):
    for j in range(n):
        print(float('{:.2f}'.format(a[i][j])), end='    ')
    print('\n')
b

3.1    1.55    0.0    3.2    0.0    

1.55    3.1    0.93    0.0    1.6    

0.0    0.93    10.0    -0.93    8.0    

3.2    0.0    -0.93    3.1    -0.31    

0.0    1.6    8.0    -0.31    3.1    



array([ -2.6195,  -2.511 , -14.6717,  -2.0778,  -9.426 ])

Обратный ход

In [163]:
array_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    array_1[k] = ((b[k] - sum([a[k][j] * array_1[j] for j in range(k + 1, n)])) / a[k][k])

In [164]:
for i in range(n):
    print(float('{:.10f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.10f}'.format(array_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  0.0  -0.62  

Определитель матрицы

In [233]:
det = 1
for i in range(n):
    for j in range(n):
        if i == j:
            det *= a[i][j]
print(det)

nan


# 2) Метод Жордана–Гаусса

In [386]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

In [387]:
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]


In [388]:
for k in range(n):
    for i in range(n):
        if i != k:
            r = a[i][k] / a[k][k]
            b[i] = b[i] - (r * b[k])
            for j in range(k, n):
                a[i][j] = a[i][j] - (r * a[k][j])

In [389]:
array_2 = [1] * 5 # x
for i in range(n):
    array_2[i] = (b[i]/a[i][i])

In [390]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(array_2[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  0.0  -0.62  

# 3) Метод LU–разложения

In [391]:
NN = 16
j = 1.5 + 0.1 * NN
k = j
l = k - 0.1
m = 1
n = 5

a = np.array([[j * m, 0.5 * j, 0, 0.2 * l, 0], 
              [0.5 * j, j, 0.3 * j, 0, 0.1 * l], 
              [0, 0.3 * j, 10, -0.3 * j, 0.5 *l], 
              [0.2 * k, 0, -0.3 * j, j, -0.1 * j], 
              [0, 0.1 * k, 0.5 * k, -0.1 * j, j * m]])
b = np.array([-j + 0.05 * j * j, 
              -0.8 * j + 0.1 * j * j - 0.02 * l * j, 
              -10 + 0.03 * j * j - 0.1 * l *j, 
              -0.2 * k + 0.3 * j + 0.02 * j * j, 
              0.01 * k * j - 0.5 * k - 0.2 * j * j])
linalg_solve = np.linalg.solve(a, b)

In [392]:
print_matrix()

[3.1  1.55 0.   0.6  0.  ]
[1.55 3.1  0.93 0.   0.3 ]
[ 0.    0.93 10.   -0.93  1.5 ]
[ 0.62  0.   -0.93  3.1  -0.31]
[ 0.    0.31  1.55 -0.31  3.1 ]


[ -2.6195  -1.705  -10.6417   0.5022  -3.3759]


In [407]:
L = np.eye(5)
U = np.zeros((5, 5))

In [408]:
for i in range(n):
    for j in range(n):
        tmp = 0.0
        # u
        if i <= j:
            U[i][j] = a[i][j] - sum([L[i][k]*U[k][j] for k in range(i)])
        # l
        else:
            L[i][j] = (a[i][j] - sum([L[i][k]*U[k][j] for k in range(j)]))/U[j][j]

In [395]:
array_3 = [1] * 5 # y
for k in range(n):
    array_3[k] = b[k] - sum([L[k][j] * array_3[j] for j in range(k)])

In [396]:
array_3_1 = [1] * 5 # x
for k in range(n - 1, -1, -1):
    array_3_1[k] = (array_3[k] - sum([U[k][j] * array_3_1[j] for j in range(k + 1, n)]))/U[k][k]

In [397]:
for i in range(n):
    print(float('{:.5f}'.format(linalg_solve[i])), end='  ')
print('\n')
for i in range(n):
    print(float('{:.5f}'.format(array_3_1[i])), end='  ')

-1.0  0.31  -1.0  0.0  -0.62  

-1.0  0.31  -1.0  -0.0  -0.62  

Определитель матрицы

In [398]:
det = 1
for i in range(n):
    for j in range(n):
        if i == j:
            det *= U[i][j]
print(det)

567.5496936075001
